export const APP_NAME = 'LXD RWebUI';
export const APP_VER = '0.2.0';
export const LXD_SERVER = 'https://localhost:8443';

export const CONTAINERS_ERROR = 'CONTAINERS_ERROR';
export const CONTAINERS_LOADING = 'CONTAINERS_LOADING';
export const CONTAINERS_LIST_ADD = 'CONTAINERS_LIST_ADD';
export const CONTAINERS_LIST_RESET = 'CONTAINERS_LIST_RESET';
export const CONTAINERS_ITEM_SUCCESS = 'CONTAINERS_ITEM_SUCCESS';
export const CONTAINERS_ITEM_RESET = 'CONTAINERS_ITEM_RESET';

export const IMAGES_ERROR = 'IMAGES_ERROR';
export const IMAGES_LOADING = 'IMAGES_LOADING';
export const IMAGES_LIST_ADD = 'IMAGES_LIST_ADD';
export const IMAGES_LIST_RESET = 'IMAGES_LIST_RESET';
export const IMAGES_ITEM_SUCCESS = 'IMAGES_ITEM_SUCCESS';
export const IMAGES_ITEM_RESET = 'IMAGES_ITEM_RESET';

export const PROFILES_ERROR = 'PROFILES_ERROR';
export const PROFILES_LOADING = 'PROFILES_LOADING';
export const PROFILES_LIST_ADD = 'PROFILES_LIST_ADD';
export const PROFILES_LIST_RESET = 'PROFILES_LIST_RESET';
export const PROFILES_ITEM_SUCCESS = 'PROFILES_ITEM_SUCCESS';
export const PROFILES_ITEM_RESET = 'PROFILES_ITEM_RESET';
