export const APP_NAME = 'LXD RWebUI';
export const APP_VER = '0.2.0';
export const LXD_SERVER = 'https://localhost:8443';

export const CONTAINER_ITEM_ERROR = 'CONTAINER_ITEM_ERROR';
export const CONTAINER_ITEM_LOADING = 'CONTAINER_ITEM_LOADING';
export const CONTAINER_ITEM_SUCCESS = 'CONTAINER_ITEM_SUCCESS';
export const CONTAINER_ITEM_RESET = 'CONTAINER_ITEM_RESET';

export const CONTAINERS_LIST_ERROR = 'CONTAINERS_LIST_ERROR';
export const CONTAINERS_LIST_LOADING = 'CONTAINERS_LIST_LOADING';
export const CONTAINERS_LIST_SUCCESS = 'CONTAINERS_LIST_SUCCESS';
export const CONTAINERS_LIST_ADD = 'CONTAINERS_LIST_ADD';
export const CONTAINERS_LIST_RESET = 'CONTAINERS_LIST_RESET';


